# Generated by Django 5.1.7 on 2025-03-24 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_book_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_add_time',
            field=models.TimeField(default=datetime.datetime(2025, 3, 24, 14, 40, 44, 175571, tzinfo=datetime.timezone.utc)),
        ),
    ]
